name: Snake
description: Snake web game built with Dart and HTML5 Canvas
# version: 1.0.0
#homepage: https://www.example.com
#author: johnnydevx <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0